apiVersion: v1
kind: ConfigMap
metadata:
    name: taskboard-config
data:
    POSTGRES_DB: taskboard
    POSTGRES_USER: taskuser
    POSTGRES_PASSWORD: taskpass
    API_HTTP_PORT: "8080"
    WEB_HTTP_PORT: "80"
