services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  go-service:
    build: ./go-service
    container_name: go-service
    ports:
      - "8081:8081"

  py-service:
    build: ./py-service
    container_name: py-service
    ports:
      - "8082:8082"

  cs-service:
    build: ./cs-service
    container_name: cs-service
    ports:
      - "8083:8083"
