apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-api-to-db
  namespace: taskboard
spec:
  podSelector:
    matchLabels:
      app: taskboard
      tier: api
  policyTypes: ["Egress"]
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: taskboard
              tier: db
      ports:
        - protocol: TCP
          port: 5432